package generate

import (
	"fmt"
	"os"
	"os/exec"
)

func generateToRepo(zipBytes []byte, repoURL string, force bool) error {
	if !force && remoteHasKikplateOrigin(repoURL) {
		return fmt.Errorf("remote %q already contains a kikplate project; use --force to overwrite", repoURL)
	}

	tmpDir, err := os.MkdirTemp("", "kikplate-gen-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	if err := unzipInto(zipBytes, tmpDir); err != nil {
		return err
	}

	for _, step := range [][]string{
		{"init"},
		{"add", "."},
		{"commit", "-m", "Initial project generated by kikplate"},
		{"remote", "add", "origin", repoURL},
	} {
		if err := runGit(tmpDir, step...); err != nil {
			return fmt.Errorf("git %s failed: %w", step[0], err)
		}
	}

	pushArgs := []string{"push", "-u", "origin", "HEAD"}
	if force {
		pushArgs = append(pushArgs, "--force")
	}
	if err := runGit(tmpDir, pushArgs...); err != nil {
		return fmt.Errorf("git push failed: %w", err)
	}

	fmt.Printf("Project pushed to: %s\n", repoURL)
	return nil
}

func runGit(dir string, args ...string) error {
	c := exec.Command("git", args...)
	c.Dir = dir
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr
	return c.Run()
}

func remoteHasKikplateOrigin(remoteURL string) bool {
	tmpDir, err := os.MkdirTemp("", "kikplate-check-*")
	if err != nil {
		return false
	}
	defer os.RemoveAll(tmpDir)

	c := exec.Command("git", "clone", "--depth", "1", "--no-checkout", remoteURL, tmpDir)
	c.Stdout = nil
	c.Stderr = nil
	if err := c.Run(); err != nil {
		return false
	}

	checkout := exec.Command("git", "checkout", "HEAD", "--", ".kikplate.origin")
	checkout.Dir = tmpDir
	checkout.Stdout = nil
	checkout.Stderr = nil
	return checkout.Run() == nil
}
